version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_started
    restart: on-failure
  database:
    image: mysql:8
    environment:
      MYSQL_DATABASE: online_ordering_db
      MYSQL_ROOT_PASSWORD: online_ordering_root_password
      MYSQL_USER: online_ordering_user
      MYSQL_PASSWORD: online_ordering_password
    ports:
      - "3306:3306"