version: '3'

services:
  database:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_DATABASE: online_ordering_db
      MYSQL_ROOT_PASSWORD: online_ordering_root_password
      MYSQL_USER: online_ordering_user
      MYSQL_PASSWORD: online_ordering_password
    ports:
      - "3306:3306"