name: Continuous Integration Workflow

on:
  workflow_dispatch:

  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  continuous_integration_artifact:
    name: Continuous Integration Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 20
          distribution: 'temurin'

      - name: package with Maven
        run: mvn package

      - name: Run pwd
        run: |
          pwd

      - name: Run ${{ github.workspace }}
        run: |
          echo ${{ github.workspace }}/target

      - name: echo ${{ github.workspace }}
        run: |
          echo ${{ github.workspace }}/target

      - uses: actions/upload-artifact@v3
        with:
          name: online_ordering
          path: ${{ github.workspace }}/target/*.jar.original




#[INFO] The original artifact has been renamed to /home/runner/work/online-ordering/online-ordering/target/online_ordering-0.0.1-SNAPSHOT.jar.original
#/home/runner/work/online-ordering/online-ordering/target/online_ordering-0.0.1-SNAPSHOT.jar.original